name: PeleC-Docs

on:
  push:
    branches: [development]
    paths:
       - 'Docs/**'
       - '.github/workflows/docs.yml'
  pull_request:
    branches: [development]
    paths:
       - 'Docs/**'
       - '.github/workflows/docs.yml'

jobs:
  Docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup
        run: |
          cmake -E make_directory ${{runner.workspace}}/build-docs
      - name: Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Dependencies
        run: |
          #Currently ignoring doxygen
          #export DEBIAN_FRONTEND=noninteractive
          #sudo apt-get update
          #sudo apt-get install -y --no-install-recommends doxygen graphviz
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme
      - name: Configure
        working-directory: ${{runner.workspace}}/build-docs
        run:  |
          cmake \
            -DPELEC_ENABLE_DOCUMENTATION:BOOL=ON \
            ${GITHUB_WORKSPACE}
      - name: Build
        working-directory: ${{runner.workspace}}/build-docs
        run:  |
           make docs
           touch ${{runner.workspace}}/build-docs/Docs/sphinx/html/.nojekyll
      - name: Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/development'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ${{runner.workspace}}/build-docs/Docs/sphinx/html
          SINGLE_COMMIT: true
